spring:
  application:
    name: sanford-ui

  mvc:
    async:
      request-timeout: ${SPRING_MVC_ASYNC_REQUEST_TIMEOUT:-1}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      enabled: true
      show-values: ALWAYS
    configprops:
      enabled: true
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus,sbom
  tracing:
    sampling:
      probability: 1.0

app:
  supportedContentTypes:
    md: text/markdown
    pdf: application/pdf
    log: text/plain
    txt: text/plain
    csv: text/csv
    tsv: text/tab-separated-values
    json: application/json
    xml: application/xml
    html: text/html
    htm: text/html
    doc: application/msword
    docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    ppt: application/vnd.ms-powerpoint
    pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
  supportedFileFilters:
    md: "(?i).+\\.md$"
    pdf: "(?i).+\\.pdf$"
    log: "(?i).+\\.log$"
    txt: "(?i).+\\.txt$"
    csv: "(?i).+\\.csv$"
    tsv: "(?i).+\\.tsv$"
    json: "(?i).+\\.json$"
    xml: "(?i).+\\.xml$"
    html: "(?i).+\\.html?$"
    doc: "(?i).+\\.docx?$"
    ppt: "(?i).+\\.pptx?$"

document:
  service:
    scheme: ${DOCUMENT_SERVICE_SCHEME:http}
    host: ${DOCUMENT_SERVICE_HOST:localhost}
    port: ${DOCUMENT_SERVICE_PORT:8080}
    url: ${document.service.scheme}://${document.service.host}:${document.service.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"