spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:///dev/urandom -XX:+UseZGC -XX:+UseStringDeduplication"
        - name: DOCUMENT_SERVICE_SCHEME
          value: "http"
        - name: DOCUMENT_SERVICE_HOST
          value: sanford.default.svc.cluster.local
        - name: DOCUMENT_SERVICE_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: default,cloud
